version: 2
jobs:
  build:
    docker:
      - image: python:3.6
        environment:
          CONDA_ENV_FILE: .travis/environment_py27.yaml
          DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: agdcintegration
          POSTGRES_PASSWORD: ""
    working_directory: ~/datacube-core
    steps:
          # Create Postgres users and database
      # Note the YAML heredoc '|' for nicer formatting
      # - run: |
      #     sudo -u root createuser -h localhost --superuser ubuntu &&
      #     sudo createdb -h localhost test_db
      - run:
          name: Install Conda + Setup Conda
          working_directory: ~
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -f -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda config --show-sources
            conda config --show
            conda config --prepend channels conda-forge
            conda update --all
            conda info -a

      - checkout

      - run:
          name: Setup Environment
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            conda env create -q -n agdc --file .travis/environment_py35.yaml
            source activate agdc
            conda install -q sphinx sphinx_rtd_theme mock click # Stuff for docs
            pip install .[analytics,test,interactive,docs] --no-deps --upgrade

      # - restore_cache:
      #     key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # - run: yarn && pip install -r requirements.txt
      # - save_cache:
      #     key: datacube-core-{{ .Branch }}-{{ checksum "yarn.lock" }}
      #     paths:
      #       - "/home/ubuntu/.yarn-cache"
      
      - run:
          name: Run All Tests
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            source activate agdc
            ./check-code.sh integration_tests

      - run:
          name: Build Documentation
          working_directory: ~/datacube-core/docs
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            source activate agdc
            make html

      # - store_artifacts:
      #     path: test-reports/coverage
      #     destination: reports
      - store_artifacts:
          path: docs/_build/html
          destination: docs
      # - store_test_results:
      #     path: "test-reports/"